from pathlib import Path
import json,base64,html,hashlib,zipfile,difflib
import numpy as np,pandas as pd
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
BASE=Path(__file__).resolve().parents[1];OUT=BASE/'output'
def write_csv(df,path):
 raw=df.to_csv(index=False).encode();temp=path.with_suffix('.csv.tmp');temp.write_bytes(raw)
 assert temp.read_bytes()==raw
 temp.replace(path)
 assert path.read_bytes()==raw

r=json.loads((OUT/'comparison.json').read_text());symbols=['BTCUSDT','ETHUSDT','SOLUSDT','XRPUSDT','ADAUSDT'];dates={'full':('2021-10-05','2026-10-05'),'train':('2021-10-05','2025-01-01'),'oos':('2025-01-01','2026-10-05')};names={'full':'کل پنج سال','train':'Train: 2021–2024','oos':'Validation: 2025–2026'};labels={'before':'گیت، بدون حاشیه ATR','after':'آزمایش تریل با حاشیه 0.25 ATR'}
cols=['symbol_index','entry_ms','exit_ms','side_sign','entry_price','quantity','initial_sl','r_distance','exit_price','gross_pnl','fees','funding_pnl','net_pnl','exit_reason_code','entry_equity','risk_usd','funding_proxy_count','root_unit_id','leg_index']
ledgers={};curves={};extra={};summaries=[]
for version in r:
 for period,m in r[version].items():
  z=np.load(OUT/f'{version}_{period}.npz');t=z['trades'];d=pd.DataFrame(t,columns=cols);d['symbol']=[symbols[int(x)] for x in d.symbol_index];d['side']=np.where(d.side_sign==1,'LONG','SHORT');d['entry_utc']=pd.to_datetime(d.entry_ms,unit='ms',utc=True).astype(str);d['exit_utc']=pd.to_datetime(d.exit_ms,unit='ms',utc=True).astype(str);d['hours_open']=(d.exit_ms-d.entry_ms)/3600000;d['net_r']=d.net_pnl/d.risk_usd;d['leg']=np.where(d.leg_index==0,'BASE','ADD');d['exit_reason']=d.exit_reason_code.map({3:'STOP',7:'CLOSED_CHANNEL_BREAK',8:'PERIOD_END'});d['slippage_drag']=.0002*d.quantity*(d.entry_price/(1+d.side_sign*.0002)+d.exit_price/(1-d.side_sign*.0002));d['ideal_gross']=d.gross_pnl+d.slippage_drag
  np.testing.assert_allclose(d.ideal_gross-d.slippage_drag-d.fees+d.funding_pnl,d.net_pnl,atol=1e-8)
  write_csv(d,OUT/f'{version}_{period}_trades.csv');ledgers[version,period]=d
  c=z['equity'];c=c[np.isfinite(c).all(axis=1)];c=np.vstack([[pd.Timestamp(dates[period][0],tz='UTC').timestamp()*1000,10000,10000],c]);c=pd.DataFrame(c,columns=['timestamp_ms','equity','balance']).drop_duplicates('timestamp_ms',keep='last').sort_values('timestamp_ms');c['utc']=pd.to_datetime(c.timestamp_ms,unit='ms',utc=True);c['peak']=c.equity.cummax();c['drawdown_pct']=(c.equity/c.peak-1)*100;write_csv(c,OUT/f'{version}_{period}_equity.csv');curves[version,period]=c
  neg=d[d.net_pnl<0];pos=d[d.net_pnl>0]
  e={'avg_win':float(pos.net_pnl.mean()),'avg_loss':float(neg.net_pnl.mean()),'slippage_drag':float(d.slippage_drag.sum()),'ideal_gross':float(d.ideal_gross.sum()),'median_hold_h':float(d.hours_open.median()),'negative_units':len(neg),'positive_units':len(pos),'exit_reasons':d.exit_reason.value_counts().to_dict(),'directions':{s:{'units':len(d[d.side==s]),'net':float(d[d.side==s].net_pnl.sum()),'win_rate':float((d[d.side==s].net_pnl>0).mean()*100)} for s in ['LONG','SHORT']}}
  worst=int(c.drawdown_pct.argmin());peak_index=int(c.iloc[:worst+1].equity.argmax());recovery=c.iloc[worst+1:];recovery=recovery[recovery.equity>=c.iloc[peak_index].equity];e['sampled_dd']={'peak_utc':str(c.iloc[peak_index].utc),'trough_utc':str(c.iloc[worst].utc),'pct':float(-c.iloc[worst].drawdown_pct),'recovery_utc':str(recovery.iloc[0].utc) if len(recovery) else None}
  extra[version,period]=e;summaries.append(dict(version=version,period=period,**{k:v for k,v in m.items() if k!='per_symbol'},**{k:v for k,v in e.items() if not isinstance(v,dict)}))
write_csv(pd.DataFrame(summaries),OUT/'comparison.csv')
plt.rcParams.update({'figure.facecolor':'#101827','axes.facecolor':'#101827','text.color':'#e4e9f2','axes.labelcolor':'#e4e9f2','xtick.color':'#bac5d7','ytick.color':'#bac5d7','axes.edgecolor':'#435269','grid.color':'#354357','font.size':10})
for period in dates:
 fig,ax=plt.subplots(2,1,figsize=(13,7.2),sharex=True,gridspec_kw={'height_ratios':[2,1]},layout='constrained')
 for v,color,label in [('before','#4fbeff','Git baseline / ATR buffer = 0'),('after','#ff9c66','Test / ATR buffer = 0.25')]:
  c=curves[v,period];ax[0].plot(c.utc,c.equity,color=color,label=label,lw=1.1);ax[1].plot(c.utc,c.drawdown_pct,color=color,lw=.85)
 ax[0].set_ylabel('Equity (USD)');ax[1].set_ylabel('Drawdown from peak (%)');ax[0].legend(loc='upper left',facecolor='#172337',labelcolor='#e4e9f2');ax[0].set_title(f'{period.upper()} | Shared $10,000 | 5 symbols | All costs included',loc='left',pad=15);ax[1].set_ylim(min(curves['before',period].drawdown_pct.min(),curves['after',period].drawdown_pct.min())-2,1)
 for a in ax:a.grid(alpha=.45)
 fig.savefig(OUT/f'{period}_equity_drawdown.png',dpi=160);plt.close(fig)

def fmt(v):return '—' if v is None else f'{v:,.2f}'
def table(headers,rows):return '<div class="scroll"><table><thead><tr>'+''.join(f'<th>{x}</th>' for x in headers)+'</tr></thead><tbody>'+''.join('<tr>'+''.join(f'<td>{x}</td>' for x in row)+'</tr>' for row in rows)+'</tbody></table></div>'
def image(p):return '<img alt="Equity and drawdown comparison" src="data:image/png;base64,'+base64.b64encode(p.read_bytes()).decode()+'">'
parts=['''<!doctype html><html lang="fa" dir="rtl"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>مقایسه تریل ATR با نسخه گیت</title><style>body{background:#0b1220;color:#e4e9f2;font:16px/1.9 Tahoma,Arial;margin:0}main{max-width:1250px;margin:auto;padding:28px}section{background:#131e30;border:1px solid #29384d;border-radius:16px;padding:24px;margin:20px 0}h1,h2,h3{line-height:1.6;color:#f4f7fc}.bad{color:#ffad8e}.good{color:#83dab5}.scroll{overflow:auto}table{border-collapse:collapse;width:100%;font-size:14px}th,td{padding:12px;border-bottom:1px solid #334158;text-align:right;white-space:nowrap}th{color:#92cfff}img{width:100%;border-radius:10px}code{direction:ltr;display:inline-block;color:#9bd4ff}a{color:#92cfff}.muted{color:#b2bed0}</style><main><h1>بک‌تست پنج‌ساله: حاشیه ATR روی تریل Donchian</h1><p>تاریخ تهیه: ۷ اکتبر ۲۰۲۶ | سرمایه اولیه ۱۰٬۰۰۰ دلار | BTC، ETH، SOL، XRP، ADA</p>''']
b=r['before']['full'];a=r['after']['full'];parts.append(f'''<section><h2 class="bad">نتیجه: تغییر 0.25 ATR پذیرفته نشد</h2><p>با حاشیهٔ بازتر، CAGR از {fmt(b['cagr_pct'])}% به {fmt(a['cagr_pct'])}% و سود خالص از ${fmt(b['net_profit'])} به ${fmt(a['net_profit'])} رسید. بیشترین افت سرمایه از {fmt(b['max_dd_pct'])}% به {fmt(a['max_dd_pct'])}% افزایش یافت. اختلاف سود خالص ${fmt(a['net_profit']-b['net_profit'])} است.</p><p>قابلیت تنظیم حاشیه در کد و داشبورد پیاده‌سازی شد، اما <code>strategy_settings.trail_atr_buffer = 0.0</code> در تنظیمات نهایی باقی ماند. نسخهٔ نهایی از نظر رفتار معاملاتی همان پایه است؛ «بعد» در این گزارش آزمایش 0.25 ATR است، نه مقدار پیش‌فرض نهایی.</p><p>این مقایسه روی master با کامیت <code>56fc480bd191c592e9e205bb927e8eab67823b3c</code> انجام شد. فیلتر ورود ATR و منطق 4B پژوهش‌های قبلی در این کامیت نیستند و در این آزمایش اضافه نشده‌اند.</p></section>''')
parts.append('''<section><h2>دقیقاً چه چیزی تغییر کرد؟</h2><p>تریل خرید برابر کمترین کف ۱۰ کندل بستهٔ ۴ساعته، منهای 0.25×ATR(14) و تریل فروش برابر بیشترین سقف همان ۱۰ کندل، به‌اضافه 0.25×ATR شد. استاپ فقط در جهت کاهش ریسک حرکت می‌کند؛ هیچ استاپ فعال قبلی عقب برده نمی‌شود. ATR از همان کندل بسته محاسبه می‌شود.</p><p>استاپ اولیهٔ ATR2، قانون REJECT برای فاصله کمتر از ۱٫۲٪، شکست Donchian10، کوموی استاندارد، ریسک ۰٫۷۵٪، چهار اسلات، اهرم ثابت 5x، سقف مارجین ۶۰٪، توقف روزانه ۲٪ و پیرامید یک‌مرحله‌ای اصلی با ریسک نصف، یکسان نگه داشته شدند. حد سود ثابت یا سربه‌سر جدید اضافه نشد.</p><p>خروج کامل با بسته‌شدن کندل در سمت نامطلوب خط خام Donchian همچنان فعال است. در نتیجه حاشیه ATR تمام انواع خروج ناشی از سایه را به خروج بسته‌شدن کندل تبدیل نمی‌کند؛ فقط فاصلهٔ تریل قیمت را افزایش می‌دهد. کارکرد قبلی Kijun close-only تغییر نکرد.</p></section>''')
for period in dates:
 rows=[]
 for v in r:
  m=r[v][period];rows.append([labels[v],fmt(m['return_pct'])+'%',fmt(m['cagr_pct'])+'%', '$'+fmt(m['net_profit']),fmt(m['profit_factor']),fmt(m['max_dd_pct'])+'%',fmt(m['calmar']),str(m['root_entries']),str(m['pyramid_adds'])])
 parts.append(f'<section><h2>{names[period]}</h2><p dir="ltr">{dates[period][0]} ≤ UTC &lt; {dates[period][1]}</p>'+table(['نسخه','بازده کل','CAGR','سود خالص','PF','بیشترین DD','Calmar','پوزیشن پایه','افزایش حجم'],rows)+image(OUT/f'{period}_equity_drawdown.png'))
 rows=[]
 for v in r:
  m=r[v][period];e=extra[v,period];rows.append([labels[v],m['trades'],fmt(m['win_rate_pct'])+'%',fmt(e['avg_win']),fmt(e['avg_loss']),fmt(m['fees']),fmt(e['slippage_drag']),fmt(m['funding_pnl']),fmt(m['avg_margin_pct'])+'%'])
 parts.append(table(['نسخه','واحد معاملاتی','برد','میانگین برد $','میانگین باخت $','کارمزد $','اثر لغزش $','Funding خالص $','میانگین مارجین'],rows)+'<p class="muted">هر افزایش حجم یک واحد مستقل است؛ PF و درصد برد در سطح واحدها محاسبه می‌شوند. پوزیشن پایه شامل واحد پایه و افزایش حجم آن است. DD جدول از مسیر دقیقه‌ای و فازهای داخل دقیقه گرفته شده؛ نمودار به‌صورت ساعتی ذخیره شده و ممکن است پایین‌ترین افت داخل ساعت را نشان ندهد.</p></section>')
parts.append('<section><h2>سود خالص هر نماد و هر جهت</h2>')
for period in dates:
 rows=[[s,fmt(r['before'][period]['per_symbol'][s]['net_profit']),fmt(r['after'][period]['per_symbol'][s]['net_profit']),fmt(r['after'][period]['per_symbol'][s]['net_profit']-r['before'][period]['per_symbol'][s]['net_profit'])] for s in symbols]
 parts.append(f'<h3>{names[period]}</h3>'+table(['نماد','قبل $','آزمایش ATR $','تغییر $'],rows))
parts.append(table(['دوره','جهت','قبل $','آزمایش ATR $','تعداد قبل / بعد'],[[names[p],s,fmt(extra['before',p]['directions'][s]['net']),fmt(extra['after',p]['directions'][s]['net']),f"{extra['before',p]['directions'][s]['units']} / {extra['after',p]['directions'][s]['units']}"] for p in dates for s in ['LONG','SHORT']])+'</section>')
parts.append('<section><h2>بررسی مسیر خروج و افت سرمایه</h2>'+table(['نسخه / دوره','Stop','شکست خط با Close','پایان دوره','میانه مدت معامله h'],[[labels[v]+' / '+names[p],extra[v,p]['exit_reasons'].get('STOP',0),extra[v,p]['exit_reasons'].get('CLOSED_CHANNEL_BREAK',0),extra[v,p]['exit_reasons'].get('PERIOD_END',0),fmt(extra[v,p]['median_hold_h'])] for v in r for p in dates]))
parts.append(table(['نسخه','قله قبل از افت ساعتی','کف افت ساعتی','بازیابی قله'],[[labels[v],extra[v,'full']['sampled_dd']['peak_utc'],extra[v,'full']['sampled_dd']['trough_utc'],extra[v,'full']['sampled_dd']['recovery_utc'] or 'تا پایان دوره بازیابی نشده'] for v in r])+'<p>کاهش تعداد برخوردهای تریل، به‌تنهایی به معنی کاهش ضرر نیست: خروج دیرتر می‌تواند زیان هر واحد یا برگشت سود را بزرگ‌تر کند. تغییر زمان خروج همچنین اسلات‌های آزاد، ورودهای بعدی و اندازه معاملات بعدی را عوض می‌کند؛ اختلاف کل پرتفوی را نمی‌توان صرفاً «تعداد سایه‌هایی که نجات یافتند» نامید.</p></section>')
# exact common-entry comparison, explicitly not a controlled causal experiment
x=ledgers['before','full'];y=ledgers['after','full'];keys=['symbol_index','entry_ms','side_sign','leg_index'];joined=x.merge(y,on=keys,suffixes=('_before','_after'));converted=((joined.net_pnl_before<0)&(joined.net_pnl_after>0)).sum();lost=((joined.net_pnl_before>0)&(joined.net_pnl_after<0)).sum()
parts.append(f'<section><h2>ورودهای مشترک؛ بررسی محدود</h2><p>{len(joined)} واحد دارای نماد، جهت، زمان ورود و نوع واحد یکسان‌اند. در این گروه {converted} باخت نسخهٔ پایه به سود تبدیل شده و {lost} برد نسخهٔ پایه به باخت تبدیل شده است. این آمار آزمون علّی مستقل نیست: حجم بر اثر تغییر سرمایه متفاوت شده و مسیر ورودهای غیرمشترک نیز تغییر کرده است.</p></section>')
parts.append('''<section><h2>هزینه‌ها، داده و اعتبارسنجی</h2><p>بازه دقیق ۵ اکتبر ۲۰۲۱ تا ابتدای ۵ اکتبر ۲۰۲۶ است؛ هر نماد 2,629,440 کندل یک‌دقیقه‌ای دارد. SHA256 آرشیوها و آرایه قیمت هر پنج نماد با ورودی‌های آزمایش اصلی تطبیق داده شد؛ پیوستگی دقیقه‌ها و اعتبار OHLC بررسی شدند. داده گرم‌کردن اندیکاتورها قبل از شروع معامله استفاده شده است.</p><p>کارمزد 0.06% در هر طرف (0.12% رفت‌وبرگشت) و لغزش نامطلوب 2bps در هر ورود و خروج اعمال شده‌اند. اثر لغزش در قیمت پرشده و سود ناخالص گنجانده شده؛ ستون «اثر لغزش» برای توضیح است و دوباره از سود کم نمی‌شود. Funding مشاهده‌شدهٔ Binance تا پایان سپتامبر ۲۰۲۶ لحاظ شد؛ برای اول تا چهارم اکتبر ۲۰۲۶، هزینهٔ محافظه‌کارانهٔ 0.01% هر ۸ ساعت جایگزین داده ناموجود شده است. تعداد رویدادهای جایگزین برای هر اجرای مستقل در CSV نتایج آمده است.</p><p>موتور، پنجره اندیکاتور ۱۹۹ کندل بستهٔ نسخهٔ ربات را بازتولید می‌کند. برای هر نماد ۶ پنجرهٔ ۴ساعتهٔ استاندارد با اندیکاتورهای runtime مقایسه شد (۳۰ کنترل در این اجرای متمرکز). نتایج پایهٔ هر سه دوره برای سود خالص، CAGR، DD، کارمزد، Funding، تعداد واحد، پوزیشن پایه و افزایش حجم با مرجع master تطبیق عددی داشتند.</p><p>Train و Validation هرکدام مستقل از ۱۰٬۰۰۰ دلار آغاز شده و در انتهای بازه بسته می‌شوند؛ جمع سود دو برش برابر سود Full نیست. ۲۰۲۵–۲۰۲۶ قبلاً برای انتخاب استراتژی بررسی شده، بنابراین آزمون کاملاً ندیده محسوب نمی‌شود.</p><p>مسیر داخل کندل دقیقه‌ای با فرض adverse-first و ترتیب پردازش مشترک نمادها شبیه‌سازی شده؛ مدل نقدشوندگی دفتر سفارش، لیکوییدیشن بر مبنای mark price و مشخصات قرارداد واقعی LBank ندارد. این نتایج پژوهشی با اجرای واقعی LBank برابر فرض نمی‌شوند.</p></section>''')
parts.append('<section><h2>تصمیم و فایل‌ها</h2><p>برای هدف کاهش بیشترین افت سرمایه، این تغییر روی master فعلی مردود است. مقدار پیش‌فرض صفر حفظ شد؛ حاشیه 0.25 فقط به‌عنوان آزمایش مستند است. برای سنجش روی نسخهٔ پژوهشی ATR-entry + 4B باید همان نسخه جداگانه مبنا قرار گیرد؛ ارقام دو مبنا با هم ترکیب نشده‌اند.</p><p>فایل comparison.csv، دفتر معاملات و منحنی ساعتی شش اجرا، کد بازتولید، هش ورودی‌ها و وصلهٔ کد در بستهٔ همراه قرار دارند.</p></section></main></html>')
(OUT/'report_atr_comparison_fa.html').write_text(''.join(parts),encoding='utf-8')
(OUT/'diagnostics.json').write_text(json.dumps({f'{v}_{p}':e for (v,p),e in extra.items()},indent=2))
patch=[]
for name in ['config.json','lbank_bot.py','strategy_archetypes.py','dashboard_server.py','tests/test_capital_management.py','tests/test_ui.cjs']:
 src=BASE/'source/lbank_project'/name;dst=BASE/'work'/name
 patch.extend(difflib.unified_diff(src.read_text().splitlines(True),dst.read_text().splitlines(True),fromfile='a/lbank_project/'+name,tofile='b/lbank_project/'+name))
(OUT/'atr_update.patch').write_text(''.join(patch))
meta={'source_commit':'56fc480bd191c592e9e205bb927e8eab67823b3c','tested_buffer':.25,'production_default':0.,'decision':'REJECT_0.25_ATR','data_coverage':json.loads((BASE/'source/high_cagr/output/coverage.json').read_text()),'parity_windows_actual':30,'risk':.0075,'slots':4,'start':'2021-10-05','end_exclusive':'2026-10-05','changes':'buffer stop candidate only; raw close-through unchanged; baseline original pyramid; no ATR entry gate or 4B'}
(OUT/'audit_manifest.json').write_text(json.dumps(meta,indent=2))
print('REPORT READY',OUT/'report_atr_comparison_fa.html')
